### ISSUE TITLE
Discoverability could be better

### ISSUE THREAD

**Issue by tdsmith** [mozilla/protodash#12]
Searching Github for "protosaur" doesn't turn anything up. Renaming the repository to match the domain might help.

**Comment by wlach** [comment]
I added a cookbook on (specifically) protosaur for DTMO here, which should hopefully help with the discoverability part: https://github.com/mozilla/firefox-data-docs/pull/553

I suspect that eventually this repository/source might be used for supporting non-prototype sites (e.g. #17) so if anything I'd be inclined to move towards a name less tied to prototyping. 😄

**Comment by tdsmith** [comment]
b1cdacb9ee317fe641285008454d44d2544c0283 probably also solved for this use case pretty well, so I'm happy to declare this settled :)
