### ISSUE TITLE
Allow hosting public sites (without SSO)

### ISSUE THREAD

**Issue by tdsmith** [mozilla/protodash#16]
A couple use cases we have for public websites are:
- the WebRender dashboard, currently at https://metrics.mozilla.com/public/sguha/ds-283/dashboard.html
- mozilla.report

It would be cool to serve those here.

**Comment by wlach** [comment]
I'd like to be able to use this for the glean-dictionary. It would be ok for me if this were served under a different domain (e.g. `open.protosaur.dev`)
